name: CI / Build
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 18.12.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies
        run: pnpm i

      - name: format
        run: pnpm run format

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build
