name: Build
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils
        
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 18.12.1
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: format
        run: npm run format

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
