name: Deploy production
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils
        
      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 18.12.1
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Install dependencies
        run: pnpm i

      - name: format
        run: pnpm run format

      - name: lint
        run: pnpm run lint

      - name: tsc
        run: pnpm run tsc

      - name: build
        run: pnpm run build
        
      - name: Deploy production
        run: vc -f --prod --token ${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
